### ISSUE TITLE
Maintained

### ISSUE THREAD

**Issue by darrida** [SimpleLegal/pocket_protector#19]
Hi there! Just looking to see if this is still maintained. I've really enjoyed using it. 

Looks like there haven't been any commits for a couple of years. I'm not sure if it's because it hasn't needed that, or for a different reason.

If it's no longer updated, that's OK (you obviously have no obligation to do so), just looking to figure out if I should look at other options.

Thanks!

**Comment by mahmoud** [comment]
Oh hey @darrida sorry I must have missed the first notification and have since fixed my gmail filters :sweat_smile:. Pocket Protector is currently used in production by at least 3 products/companies, including @kurtbrose's and my own (the original authors, in other words). So should anything arise, it's fair to assume we'll have to fix our precious `pprotect`. Sorry for the delay and thanks for the kind words!

**Comment by darrida** [comment]
Thanks so much for the response!
